#!/bin/bash

set -xe

vagrant ssh management -c '
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.12.0-alpha.3/kubevirt.yaml &&
kubectl create configmap -n kubevirt kubevirt-config --from-literal debug.useEmulation=true
'
