apiVersion: nmstate.io/v1
kind: NodeNetworkState
metadata:
  creationTimestamp: null
  name: 192.168.122.101
  namespace: nmstate-default
spec:
  desiredState:
    interfaces:
    - description: OVS bridge for secondary pod networking
      name: br1
      type: ovs-bridge
      state: up
      bridge:
        options:
          fail-mode: ''
          mcast-snooping-enable: false
          rstp: false
          stp: true
        port:
        - name: eth2
          type: system
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    - description: Bridge physical interface
      name: eth2
      type: ethernet
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
  managed: true
  nodeName: node1
status:
  currentState:
    capabilities: null
    interfaces: null
